version: '3.7'

services:
  database:
    image: postgres:14-alpine
    container_name: agendador_pg
    restart: always
    ports:
      - '5433:5432' # Porta do seu PC : Porta do Container
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: agendador_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: